// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package tenant

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FreeTenantUser struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Tier      string
	DbUsage   pgtype.Int8
	DbName    pgtype.Text
	DbHost    pgtype.Text
	CreatedAt pgtype.Timestamp
}
